exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: mohsensadr
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/mohsensadr/mohsensadr.github.io"
  
title: "https://mohsensadr.github.io"
description: Primer is a Jekyll theme for GitHub Pages
